/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface KubaButton {
        "componentId": string;
        "handleSubmit": any;
    }
    interface KubaInput {
        "componentId": string;
        "inputType": "text" | "number";
        "label": string;
        "max": any;
        "maxlength": any;
        "min": any;
        "pattern": any;
        "required": any;
        "value": string;
    }
    interface KubaWizard {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLKubaButtonElement extends Components.KubaButton, HTMLStencilElement {
    }
    var HTMLKubaButtonElement: {
        prototype: HTMLKubaButtonElement;
        new (): HTMLKubaButtonElement;
    };
    interface HTMLKubaInputElement extends Components.KubaInput, HTMLStencilElement {
    }
    var HTMLKubaInputElement: {
        prototype: HTMLKubaInputElement;
        new (): HTMLKubaInputElement;
    };
    interface HTMLKubaWizardElement extends Components.KubaWizard, HTMLStencilElement {
    }
    var HTMLKubaWizardElement: {
        prototype: HTMLKubaWizardElement;
        new (): HTMLKubaWizardElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "kuba-button": HTMLKubaButtonElement;
        "kuba-input": HTMLKubaInputElement;
        "kuba-wizard": HTMLKubaWizardElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface KubaButton {
        "componentId"?: string;
        "handleSubmit"?: any;
    }
    interface KubaInput {
        "componentId"?: string;
        "inputType"?: "text" | "number";
        "label"?: string;
        "max"?: any;
        "maxlength"?: any;
        "min"?: any;
        "onInputEvent"?: (event: CustomEvent<any>) => void;
        "pattern"?: any;
        "required"?: any;
        "value"?: string;
    }
    interface KubaWizard {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "kuba-button": KubaButton;
        "kuba-input": KubaInput;
        "kuba-wizard": KubaWizard;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "kuba-button": LocalJSX.KubaButton & JSXBase.HTMLAttributes<HTMLKubaButtonElement>;
            "kuba-input": LocalJSX.KubaInput & JSXBase.HTMLAttributes<HTMLKubaInputElement>;
            "kuba-wizard": LocalJSX.KubaWizard & JSXBase.HTMLAttributes<HTMLKubaWizardElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
