/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MatchResults } from "@stencil/router";
export namespace Components {
    interface AppHome {
    }
    interface AppProfile {
        "match": MatchResults;
    }
    interface AppRoot {
    }
    interface KubaAddressForm {
    }
    interface KubaButton {
        "handleSubmit": any;
    }
    interface KubaInput {
        "componentId": string;
        "inputType": "text" | "number";
        "label": string;
    }
}
declare global {
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {
    }
    var HTMLAppProfileElement: {
        prototype: HTMLAppProfileElement;
        new (): HTMLAppProfileElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLKubaAddressFormElement extends Components.KubaAddressForm, HTMLStencilElement {
    }
    var HTMLKubaAddressFormElement: {
        prototype: HTMLKubaAddressFormElement;
        new (): HTMLKubaAddressFormElement;
    };
    interface HTMLKubaButtonElement extends Components.KubaButton, HTMLStencilElement {
    }
    var HTMLKubaButtonElement: {
        prototype: HTMLKubaButtonElement;
        new (): HTMLKubaButtonElement;
    };
    interface HTMLKubaInputElement extends Components.KubaInput, HTMLStencilElement {
    }
    var HTMLKubaInputElement: {
        prototype: HTMLKubaInputElement;
        new (): HTMLKubaInputElement;
    };
    interface HTMLElementTagNameMap {
        "app-home": HTMLAppHomeElement;
        "app-profile": HTMLAppProfileElement;
        "app-root": HTMLAppRootElement;
        "kuba-address-form": HTMLKubaAddressFormElement;
        "kuba-button": HTMLKubaButtonElement;
        "kuba-input": HTMLKubaInputElement;
    }
}
declare namespace LocalJSX {
    interface AppHome {
    }
    interface AppProfile {
        "match"?: MatchResults;
    }
    interface AppRoot {
    }
    interface KubaAddressForm {
    }
    interface KubaButton {
        "handleSubmit"?: any;
    }
    interface KubaInput {
        "componentId"?: string;
        "inputType"?: "text" | "number";
        "label"?: string;
        "onInputEvent"?: (event: CustomEvent<any>) => void;
    }
    interface IntrinsicElements {
        "app-home": AppHome;
        "app-profile": AppProfile;
        "app-root": AppRoot;
        "kuba-address-form": KubaAddressForm;
        "kuba-button": KubaButton;
        "kuba-input": KubaInput;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-profile": LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "kuba-address-form": LocalJSX.KubaAddressForm & JSXBase.HTMLAttributes<HTMLKubaAddressFormElement>;
            "kuba-button": LocalJSX.KubaButton & JSXBase.HTMLAttributes<HTMLKubaButtonElement>;
            "kuba-input": LocalJSX.KubaInput & JSXBase.HTMLAttributes<HTMLKubaInputElement>;
        }
    }
}
